import Link from "next/link";
import { ArrowLeft, CheckCircle2, MessageCircle, Pencil, RotateCcw, Trash2 } from "lucide-react";
import { notFound } from "next/navigation";
import { deletePost, deleteReply, editPost, editReply, replyToPost, togglePostResolved } from "@/app/actions";
import { Badge } from "@/components/app-shell";
import { requireUser } from "@/lib/auth";
import { postById, replies } from "@/lib/data";
import { initials, relativeTime } from "@/lib/format";
import { isAdmin } from "@/lib/types";
export default async function PostDetail({params}:{params:Promise<{id:string}>}){
  const user=await requireUser();const {id}=await params;const [post,replyRows]=await Promise.all([postById(user,id),replies(id)]);if(!post)notFound();const canManage=post.author_id===user.id||isAdmin(user);const canEdit=canManage&&(!post.resolved||isAdmin(user));
  return <article className="detail-page"><Link className="back-link" href="/staff-board"><ArrowLeft size={15}/>Back to Staff Board</Link><section className="surface post-hero"><div className="item-meta"><Badge tone={post.resolved?"success":"info"}>{post.resolved?"Resolved":post.post_type}</Badge></div><h1>{post.title}</h1><p>{post.body}</p><div className="author-line"><span className="avatar">{initials(String(post.authorName))}</span><div><strong>{post.authorName}</strong><small>{post.authorTitle} · {relativeTime(String(post.created_at))}</small></div></div><div className="card-actions">{canManage&&<form action={togglePostResolved}><input type="hidden" name="postId" value={id}/><button className="button button-secondary">{post.resolved?<><RotateCcw size={15}/>Reopen post</>:<><CheckCircle2 size={15}/>Mark resolved</>}</button></form>}{canEdit&&<details className="inline-editor"><summary className="button button-secondary"><Pencil size={14}/>Edit</summary><form action={editPost}><input type="hidden" name="postId" value={id}/><label>Title<input name="title" defaultValue={String(post.title)} required/></label><label>Details<textarea name="body" defaultValue={String(post.body)} rows={4} required/></label><label>Tags<input name="tags" defaultValue={String(post.tags)}/></label><button className="button button-primary">Save changes</button></form></details>}{canEdit&&<form action={deletePost}><input type="hidden" name="postId" value={id}/><button className="button button-secondary"><Trash2 size={14}/>Delete</button></form>}</div></section><section className="surface replies"><h2><MessageCircle size={18}/>{replyRows.length} replies</h2>{replyRows.map(reply=>{const own=reply.author_id===user.id||isAdmin(user);return <article key={reply.id}><span className="avatar">{initials(String(reply.authorName))}</span><div><header><strong>{reply.authorName}</strong><small>{relativeTime(String(reply.created_at))}{reply.edited_at?" · edited":""}</small></header><p>{reply.body}</p>{own&&<div className="reply-actions"><details><summary>Edit</summary><form action={editReply}><input type="hidden" name="replyId" value={reply.id}/><input type="hidden" name="postId" value={id}/><textarea name="body" defaultValue={String(reply.body)} rows={2} required/><button className="button button-primary">Save</button></form></details><form action={deleteReply}><input type="hidden" name="replyId" value={reply.id}/><input type="hidden" name="postId" value={id}/><button>Delete</button></form></div>}</div></article>})}<form action={replyToPost} className="reply-form"><input type="hidden" name="postId" value={id}/><label><span className="sr-only">Your reply</span><textarea name="body" rows={3} required placeholder="Write a helpful reply…"/></label><button className="button button-primary">Post reply</button></form></section></article>
}
