"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { db } from "@/lib/db";
import { requireRole, requireUser } from "@/lib/auth";
import { canCreateOfficial, isAdmin } from "@/lib/types";

const text=(f:FormData,key:string)=>String(f.get(key)??"").trim();
const checked=(f:FormData,key:string)=>f.get(key)==="on"||f.get(key)==="true";
const uuid=()=>crypto.randomUUID();
const sqlDate=(value:string)=>value?new Date(value).toISOString().replace("T"," ").slice(0,19):null;

async function target(entityType:string,entityId:string,f:FormData){
  const audienceType=text(f,"audienceType")||"all_staff"; const audienceValue=text(f,"audienceValue")||null;
  await db().execute({sql:`INSERT INTO audiences(id,entity_type,entity_id,audience_type,audience_value) VALUES (?,?,?,?,?)`,args:[uuid(),entityType,entityId,audienceType,audienceType==="all_staff"?null:audienceValue]});
}
async function audit(actorId:string,action:string,entityType:string,entityId:string,metadata:object={}){await db().execute({sql:`INSERT INTO audit_logs(id,actor_id,action,entity_type,entity_id,metadata) VALUES (?,?,?,?,?,?)`,args:[uuid(),actorId,action,entityType,entityId,JSON.stringify(metadata)]});}

export async function acknowledge(formData:FormData){const user=await requireUser();const entityType=text(formData,"entityType"),entityId=text(formData,"entityId");await db().execute({sql:`INSERT OR IGNORE INTO acknowledgements(id,entity_type,entity_id,user_id) VALUES (?,?,?,?)`,args:[uuid(),entityType,entityId,user.id]});revalidatePath("/");revalidatePath(`/${entityType==="notice"?"notices":"documents"}/${entityId}`);}

export async function createPost(formData:FormData){
  const user=await requireUser();const parsed=z.object({title:z.string().min(4).max(120),body:z.string().min(8).max(4000),postType:z.string().min(1)}).safeParse({title:text(formData,"title"),body:text(formData,"body"),postType:text(formData,"postType")});
  if(!parsed.success)redirect("/staff-board?error=validation");if(text(formData,"audienceType")==="role")formData.set("audienceValue",user.role);
  const postId=uuid();await db().execute({sql:`INSERT INTO staff_posts(id,title,body,post_type,tags,author_id) VALUES (?,?,?,?,?,?)`,args:[postId,parsed.data.title,parsed.data.body,parsed.data.postType,text(formData,"tags"),user.id]});await target("staff_post",postId,formData);revalidatePath("/staff-board");redirect(`/staff-board/${postId}`);
}
export async function replyToPost(formData:FormData){const user=await requireUser();const postId=text(formData,"postId"),body=text(formData,"body");if(body.length<2) return;await db().execute({sql:`INSERT INTO staff_replies(id,post_id,author_id,body) VALUES (?,?,?,?)`,args:[uuid(),postId,user.id,body]});const owner=await db().execute({sql:`SELECT author_id,title FROM staff_posts WHERE id=?`,args:[postId]});if(owner.rows[0]&&String(owner.rows[0].author_id)!==user.id)await db().execute({sql:`INSERT INTO notifications(id,user_id,type,entity_type,entity_id,title) VALUES (?,?,?,?,?,?)`,args:[uuid(),String(owner.rows[0].author_id),"reply","staff_post",postId,`New reply: ${String(owner.rows[0].title)}`]});revalidatePath(`/staff-board/${postId}`);}
export async function togglePostResolved(formData:FormData){const user=await requireUser();const postId=text(formData,"postId");const result=await db().execute({sql:`SELECT author_id,resolved FROM staff_posts WHERE id=?`,args:[postId]});const post=result.rows[0];if(!post||String(post.author_id)!==user.id&&!isAdmin(user)) redirect("/?denied=1");const resolved=Number(post.resolved)?0:1;await db().execute({sql:`UPDATE staff_posts SET resolved=?,resolved_at=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`,args:[resolved,resolved?new Date().toISOString():null,postId]});revalidatePath("/staff-board");revalidatePath(`/staff-board/${postId}`);}
export async function editPost(formData:FormData){const user=await requireUser();const postId=text(formData,"postId");const result=await db().execute({sql:`SELECT author_id,resolved FROM staff_posts WHERE id=?`,args:[postId]});const post=result.rows[0];if(!post||String(post.author_id)!==user.id&&!isAdmin(user)||Boolean(post.resolved)&&!isAdmin(user))redirect("/?denied=1");await db().execute({sql:`UPDATE staff_posts SET title=?,body=?,tags=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`,args:[text(formData,"title"),text(formData,"body"),text(formData,"tags"),postId]});if(String(post.author_id)!==user.id)await audit(user.id,"staff_post.moderated","staff_post",postId);revalidatePath("/staff-board");revalidatePath(`/staff-board/${postId}`);}
export async function deletePost(formData:FormData){const user=await requireUser();const postId=text(formData,"postId");const result=await db().execute({sql:`SELECT author_id,resolved FROM staff_posts WHERE id=?`,args:[postId]});const post=result.rows[0];if(!post||String(post.author_id)!==user.id&&!isAdmin(user)||Boolean(post.resolved)&&!isAdmin(user))redirect("/?denied=1");if(String(post.author_id)!==user.id)await audit(user.id,"staff_post.deleted","staff_post",postId);await db().execute({sql:`DELETE FROM staff_posts WHERE id=?`,args:[postId]});revalidatePath("/staff-board");redirect("/staff-board");}
export async function editReply(formData:FormData){const user=await requireUser();const replyId=text(formData,"replyId"),postId=text(formData,"postId");const result=await db().execute({sql:`SELECT author_id FROM staff_replies WHERE id=?`,args:[replyId]});const reply=result.rows[0];if(!reply||String(reply.author_id)!==user.id&&!isAdmin(user))redirect("/?denied=1");await db().execute({sql:`UPDATE staff_replies SET body=?,edited_at=CURRENT_TIMESTAMP WHERE id=?`,args:[text(formData,"body"),replyId]});if(String(reply.author_id)!==user.id)await audit(user.id,"staff_reply.moderated","staff_reply",replyId);revalidatePath(`/staff-board/${postId}`);}
export async function deleteReply(formData:FormData){const user=await requireUser();const replyId=text(formData,"replyId"),postId=text(formData,"postId");const result=await db().execute({sql:`SELECT author_id FROM staff_replies WHERE id=?`,args:[replyId]});const reply=result.rows[0];if(!reply||String(reply.author_id)!==user.id&&!isAdmin(user))redirect("/?denied=1");if(String(reply.author_id)!==user.id)await audit(user.id,"staff_reply.deleted","staff_reply",replyId);await db().execute({sql:`DELETE FROM staff_replies WHERE id=?`,args:[replyId]});revalidatePath(`/staff-board/${postId}`);}

export async function createNotice(formData:FormData){
  const user=await requireUser();if(!canCreateOfficial(user))redirect("/?denied=1");
  if(text(formData,"audienceType")!=="all_staff"&&!text(formData,"audienceValue"))redirect("/admin/notices?error=scope");
  if(user.role==="department_head"&&(text(formData,"audienceType")!=="department"||text(formData,"audienceValue")!==user.departmentId))redirect("/admin/notices?error=scope");
  const priority=text(formData,"priority"),noticeId=uuid();const publishAt=sqlDate(text(formData,"publishAt"))??new Date().toISOString().replace("T"," ").slice(0,19);const expiresAt=sqlDate(text(formData,"expiresAt"));const status=new Date(publishAt)>new Date()?"scheduled":"published";
  await db().execute({sql:`INSERT INTO notices(id,title,body,category,priority,publish_at,expires_at,acknowledgement_required,author_id,status) VALUES (?,?,?,?,?,?,?,?,?,?)`,args:[noticeId,text(formData,"title"),text(formData,"body"),text(formData,"category"),priority,publishAt,expiresAt,checked(formData,"acknowledgementRequired")?1:0,user.id,status]});
  await target("notice",noticeId,formData);await audit(user.id,"notice.created","notice",noticeId,{priority,status});revalidatePath("/");revalidatePath("/notices");revalidatePath("/admin/notices");
}
export async function archiveNotice(formData:FormData){
  const user=await requireRole(["department_head","admin","system_admin"]);const noticeId=text(formData,"noticeId");
  if(user.role==="department_head"){const owned=await db().execute({sql:`SELECT 1 FROM notices WHERE id=? AND author_id=?`,args:[noticeId,user.id]});if(!owned.rows.length)redirect("/admin/notices?error=scope");}
  await db().execute({sql:`UPDATE notices SET status='archived',updated_at=CURRENT_TIMESTAMP WHERE id=?`,args:[noticeId]});await audit(user.id,"notice.archived","notice",noticeId);revalidatePath("/");revalidatePath("/notices");revalidatePath("/admin/notices");
}

export async function createEvent(formData:FormData){const user=await requireRole(["admin","system_admin"]);const eventId=uuid();await db().execute({sql:`INSERT INTO events(id,title,description,start_at,end_at,all_day,location,category,organizer_id) VALUES (?,?,?,?,?,?,?,?,?)`,args:[eventId,text(formData,"title"),text(formData,"description"),sqlDate(text(formData,"startAt")),sqlDate(text(formData,"endAt")),checked(formData,"allDay")?1:0,text(formData,"location"),text(formData,"category"),user.id]});await target("event",eventId,formData);await audit(user.id,"event.created","event",eventId);revalidatePath("/events");revalidatePath("/admin/content");}
export async function createDocument(formData:FormData){const user=await requireRole(["admin","system_admin"]);const documentId=uuid();const url=z.string().url().safeParse(text(formData,"url"));if(!url.success)redirect("/admin/content?error=url");await db().execute({sql:`INSERT INTO documents(id,title,description,category,department_id,external_url,version,effective_date,pinned,acknowledgement_required,updated_by) VALUES (?,?,?,?,?,?,?,?,?,?,?)`,args:[documentId,text(formData,"title"),text(formData,"description"),text(formData,"category"),text(formData,"departmentId")||null,url.data,text(formData,"version"),text(formData,"effectiveDate")||null,checked(formData,"pinned")?1:0,checked(formData,"acknowledgementRequired")?1:0,user.id]});await target("document",documentId,formData);await audit(user.id,"document.created","document",documentId);revalidatePath("/documents");revalidatePath("/admin/content");}
export async function createQuickLink(formData:FormData){const user=await requireRole(["admin","system_admin"]);const linkId=uuid();const url=z.string().url().safeParse(text(formData,"url"));if(!url.success)redirect("/admin/content?error=url");await db().execute({sql:`INSERT INTO quick_links(id,label,url,description,category,sort_order) VALUES (?,?,?,?,?,?)`,args:[linkId,text(formData,"label"),url.data,text(formData,"description"),text(formData,"category"),Number(text(formData,"sortOrder"))||0]});await target("quick_link",linkId,formData);await audit(user.id,"quick_link.created","quick_link",linkId);revalidatePath("/links");revalidatePath("/admin/content");}
export async function updateUser(formData:FormData){const actor=await requireRole(["system_admin"]);const userId=text(formData,"userId");if(userId===actor.id&&!checked(formData,"active"))return;await db().execute({sql:`UPDATE users SET role=?,department_id=?,active=? WHERE id=?`,args:[text(formData,"role"),text(formData,"departmentId")||null,checked(formData,"active")?1:0,userId]});await audit(actor.id,"user.updated","user",userId,{role:text(formData,"role"),active:checked(formData,"active")});revalidatePath("/admin/users");}
export async function createDepartment(formData:FormData){const actor=await requireRole(["system_admin"]);const name=text(formData,"name");if(name.length<2)return;const departmentId=uuid();await db().execute({sql:`INSERT INTO departments(id,name) VALUES (?,?)`,args:[departmentId,name]});await audit(actor.id,"department.created","department",departmentId,{name});revalidatePath("/admin/users");}
