import Link from "next/link";
import { ArrowRight, Bell, BookOpen, CalendarDays, CheckCircle2, ClipboardCheck, ExternalLink, MessageSquare, Search } from "lucide-react";
import { acknowledge } from "@/app/actions";
import { Badge, EmptyState, PageHeader } from "@/components/app-shell";
import { requireUser } from "@/lib/auth";
import { documents, events, hasAcknowledged, notices, posts, quickLinks } from "@/lib/data";
import { coverBoard } from "@/lib/cover";
import { markdownSnippet, prettyDateTime, relativeTime, schoolDate, snippet } from "@/lib/format";

export default async function Dashboard({searchParams}:{searchParams:Promise<{denied?:string}>}){
  const user=await requireUser();const [noticeRows,eventRows,postRows,documentRows,linkRows,coverRows,params]=await Promise.all([notices(user),events(user),posts(user),documents(user),quickLinks(user),coverBoard(schoolDate(),user.id),searchParams]);
  const urgent=noticeRows.filter((n)=>n.priority==="critical"||n.priority==="important").slice(0,3);const todayEvents=eventRows.slice(0,4);const openPosts=postRows.slice(0,3);const pinnedDocs=documentRows.filter((d)=>d.pinned).slice(0,3);
  return <>
    <PageHeader eyebrow={new Intl.DateTimeFormat("en-SG",{weekday:"long",day:"numeric",month:"long"}).format(new Date()).toUpperCase()} title={`Good morning, ${user.fullName.split(" ")[0]}`} description="Here’s what affects you today." actions={<><Link className="search-trigger" href="/search"><Search size={16}/>Search the hub</Link><Link className="icon-button" href="/notifications" aria-label="Notifications"><Bell size={19}/></Link></>}/>
    {params.denied&&<div className="notice-inline notice-warning">You do not have permission to open that area.</div>}
    <section className="urgent-stack" aria-label="Priority notices">{urgent.map(async(n)=>{const ack=await hasAcknowledged(user.id,"notice",n.id);return <article className={`urgent-item priority-${n.priority}`} key={n.id}><div><div className="item-meta"><Badge tone={n.priority==="critical"?"critical":"important"}>{String(n.priority).toUpperCase()}</Badge>{Boolean(n.acknowledgement_required)&&<Badge>{ack?"Acknowledged":"Action required"}</Badge>}</div><Link href={`/notices/${n.id}`}><h2>{n.title}</h2></Link><p>{markdownSnippet(String(n.body),180)}</p></div>{Boolean(n.acknowledgement_required)&&!ack?<form action={acknowledge}><input type="hidden" name="entityType" value="notice"/><input type="hidden" name="entityId" value={n.id}/><button className="button button-danger"><CheckCircle2 size={16}/>Acknowledge</button></form>:<Link className="text-link" href={`/notices/${n.id}`}>View <ArrowRight size={14}/></Link>}</article>})}{urgent.length===0&&<EmptyState title="You’re all caught up" description="There are no priority notices for you."/>}</section>
    <div className="section-title"><div><p className="eyebrow">YOUR DAY</p><h2>Today at a glance</h2></div></div>
    <div className="home-grid"><section className="surface"><div className="surface-header"><h3><CalendarDays size={17}/>Upcoming</h3><Link href="/events">View all</Link></div><div className="list">{todayEvents.map((event)=><Link className="list-row" href="/events" key={event.id}><span className="date-tile"><strong>{new Date(String(event.start_at)).getDate()}</strong><small>{new Intl.DateTimeFormat("en",{month:"short"}).format(new Date(String(event.start_at)))}</small></span><div><strong>{event.title}</strong><p>{event.location||event.category} · {prettyDateTime(String(event.start_at))}</p></div></Link>)}</div></section>
      <section className="surface"><div className="surface-header"><h3><ClipboardCheck size={17}/>Cover today</h3><Link href="/cover">View board</Link></div><div className="list">{coverRows.slice(0,4).map(slot=><Link className="list-row" href="/cover" key={slot.id}><span className="date-tile"><strong>{slot.period}</strong><small>Period</small></span><div><strong>{slot.className} · {slot.subject}</strong><p>{slot.absentStaffName} · {slot.assignedUserName??"Cover needed"}</p></div></Link>)}{coverRows.length===0&&<div className="home-empty"><CheckCircle2 size={18}/><span>No cover requirements today</span></div>}</div></section>
      <section className="surface"><div className="surface-header"><h3><MessageSquare size={17}/>Staff board</h3><Link href="/staff-board">View all</Link></div><div className="list">{openPosts.map((post)=><Link className="list-row" href={`/staff-board/${post.id}`} key={post.id}><span className="dot-icon"><MessageSquare size={15}/></span><div><strong>{post.title}</strong><p>{snippet(String(post.body),75)}</p><small>{post.replyCount} replies · {relativeTime(String(post.created_at))}</small></div></Link>)}</div></section>
      <section className="surface"><div className="surface-header"><h3><BookOpen size={17}/>Pinned documents</h3><Link href="/documents">View all</Link></div><div className="list">{pinnedDocs.map((doc)=><Link className="list-row" href={`/documents?open=${doc.id}`} key={doc.id}><span className="dot-icon"><BookOpen size={15}/></span><div><strong>{doc.title}</strong><p>{doc.category} · Version {doc.version||"—"}</p></div></Link>)}</div></section>
      <section className="surface"><div className="surface-header"><h3><ExternalLink size={17}/>Quick links</h3><Link href="/links">View all</Link></div><div className="quick-grid">{linkRows.slice(0,6).map((link)=><a href={String(link.url)} target="_blank" rel="noreferrer" key={link.id}><span>{String(link.label).slice(0,1)}</span><div><strong>{link.label}</strong><small>{link.category}</small></div></a>)}</div></section>
    </div>
  </>
}
