import Link from "next/link";
import { ArrowLeft, CheckCircle2, Paperclip } from "lucide-react";
import { notFound } from "next/navigation";
import { acknowledge } from "@/app/actions";
import { Badge } from "@/components/app-shell";
import { Markdown } from "@/components/markdown";
import { requireUser } from "@/lib/auth";
import { hasAcknowledged, noticeById } from "@/lib/data";
import { prettyDateTime } from "@/lib/format";
export default async function NoticeDetail({params}:{params:Promise<{id:string}>}){const user=await requireUser();const {id}=await params;const item=await noticeById(user,id);if(!item)notFound();const ack=await hasAcknowledged(user.id,"notice",id);return <article className="detail-page"><Link className="back-link" href="/notices"><ArrowLeft size={15}/>Back to notices</Link><div className={`detail-hero priority-${item.priority}`}><div className="item-meta"><Badge tone={item.priority==="critical"?"critical":item.priority==="important"?"important":"neutral"}>{item.priority}</Badge><Badge>{item.category}</Badge>{Boolean(item.acknowledgement_required)&&<Badge>{ack?"Acknowledged":"Acknowledgement required"}</Badge>}</div><h1>{item.title}</h1><p className="detail-byline">Published by {item.authorName} · {prettyDateTime(String(item.publish_at))}</p></div><div className="detail-grid"><section className="surface prose"><Markdown content={String(item.body)}/>{item.attachments!=="[]"&&<div><Paperclip size={16}/>Attachments available</div>}</section><aside className="surface detail-aside"><h3>Notice details</h3><dl><div><dt>Status</dt><dd>{item.status}</dd></div><div><dt>Published</dt><dd>{prettyDateTime(String(item.publish_at))}</dd></div>{item.expires_at&&<div><dt>Expires</dt><dd>{prettyDateTime(String(item.expires_at))}</dd></div>}</dl>{Boolean(item.acknowledgement_required)&&(ack?<div className="ack-done"><CheckCircle2 size={18}/>Acknowledged</div>:<form action={acknowledge}><input type="hidden" name="entityType" value="notice"/><input type="hidden" name="entityId" value={id}/><button className="button button-primary button-block"><CheckCircle2 size={16}/>Acknowledge notice</button></form>)}</aside></div></article>}
