import Link from "next/link";
import { ChevronRight, MessageCircle, Plus, Search } from "lucide-react";
import { createPost } from "@/app/actions";
import { Badge, EmptyState, PageHeader } from "@/components/app-shell";
import { requireUser } from "@/lib/auth";
import { posts } from "@/lib/data";
import { relativeTime, snippet } from "@/lib/format";
const types=["Question","Looking For","Help Needed","Resource Request","Resource Sharing","Volunteer Request","Lost & Found","Recommendation","Social","General"];
export default async function StaffBoard({searchParams}:{searchParams:Promise<{q?:string;resolved?:string;compose?:string;error?:string}>}){const user=await requireUser();const p=await searchParams;const items=await posts(user,p.resolved==="1",p.q??"");return <><PageHeader eyebrow="TEACHER COMMUNITY" title="Staff Board" description="Ask colleagues, share resources, and find help." actions={<Link className="button button-primary" href="/staff-board?compose=1"><Plus size={16}/>New post</Link>}/>{p.compose&&<section className="surface form-panel"><h2>Create a staff post</h2><form action={createPost} className="form-grid"><label className="span-2">Title<input name="title" required minLength={4} placeholder="What do you need?"/></label><label>Post type<select name="postType">{types.map((type)=><option key={type}>{type}</option>)}</select></label><label>Audience<select name="audienceType"><option value="all_staff">All staff</option><option value="department">My department</option><option value="role">Role</option></select></label><input type="hidden" name="audienceValue" value={user.departmentId??user.role}/><label className="span-2">Details<textarea name="body" required rows={4} placeholder="Add enough context for colleagues to help."/></label><label className="span-2">Tags<input name="tags" placeholder="languages, resources"/></label><div className="span-2 form-actions"><Link className="button button-secondary" href="/staff-board">Cancel</Link><button className="button button-primary">Publish post</button></div></form></section>}<form className="filter-bar"><label><Search size={16}/><input name="q" defaultValue={p.q} placeholder="Search the Staff Board"/></label><label className="check"><input name="resolved" type="checkbox" value="1" defaultChecked={p.resolved==="1"}/>Include resolved</label><button className="button button-secondary">Apply</button></form><section className="content-list community-list">{items.map((post)=><Link className={`content-row ${post.resolved?"is-resolved":""}`} href={`/staff-board/${post.id}`} key={post.id}><div className="content-row-main"><div className="item-meta"><Badge tone={post.resolved?"success":"info"}>{post.resolved?"Resolved":post.post_type}</Badge></div><h2>{post.title}</h2><p>{snippet(String(post.body),180)}</p><small>{post.authorName} · {relativeTime(String(post.created_at))} · <MessageCircle size={12}/>{post.replyCount} replies</small></div><ChevronRight size={18}/></Link>)}{items.length===0&&<EmptyState title="No posts found" description="Start a conversation or broaden your filters."/>}</section></>}
