import { Plus, Save } from "lucide-react";
import { createDepartment, updateUser } from "@/app/actions";
import { Badge, PageHeader } from "@/components/app-shell";
import { requireRole } from "@/lib/auth";
import { db, rows } from "@/lib/db";
type Person={id:string;full_name:string;email:string;job_title:string;role:string;department_id:string;active:number};type Department={id:string;name:string};
export default async function AdminUsers(){
  await requireRole(["system_admin"]);const [peopleResult,depsResult]=await Promise.all([db().execute(`SELECT u.*,d.name as departmentName FROM users u LEFT JOIN departments d ON d.id=u.department_id ORDER BY u.full_name`),db().execute(`SELECT id,name FROM departments WHERE active=1 ORDER BY name`)]);const people=rows<Person>(peopleResult),deps=rows<Department>(depsResult);
  return <><PageHeader eyebrow="SYSTEM ADMIN" title="Users & departments" description="Manage role, department membership and account status."/><section className="surface department-admin"><div><h2>Departments</h2><p>{deps.map(d=>d.name).join(" · ")}</p></div><form action={createDepartment}><label><span className="sr-only">Department name</span><input name="name" required placeholder="New department"/></label><button className="button button-primary"><Plus size={15}/>Add</button></form></section><section className="surface table-wrap"><table><thead><tr><th>Staff member</th><th>Role</th><th>Department</th><th>Status</th><th></th></tr></thead><tbody>{people.map(person=><tr key={person.id}><td><strong>{person.full_name}</strong><small>{person.email}<br/>{person.job_title}</small></td><td colSpan={4}><form action={updateUser} className="user-row-form"><input type="hidden" name="userId" value={person.id}/><select name="role" defaultValue={person.role}><option value="teacher">Teacher</option><option value="department_head">Department Head</option><option value="admin">Admin</option><option value="system_admin">System Admin</option></select><select name="departmentId" defaultValue={person.department_id}>{deps.map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select><label className="check"><input type="checkbox" name="active" defaultChecked={Boolean(person.active)}/><Badge tone={person.active?"success":"neutral"}>{person.active?"Active":"Inactive"}</Badge></label><button className="icon-button" aria-label={`Save ${person.full_name}`}><Save size={15}/></button></form></td></tr>)}</tbody></table></section></>
}
